# Generated by Django 4.2.4 on 2024-03-15 16:27

from django.db import migrations, models
import tyresapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tyre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('tyres_parameters', models.CharField(max_length=100)),
                ('disks_parameters', models.CharField(max_length=100)),
                ('tread_remain', models.IntegerField(default=0)),
                ('stage', models.CharField(max_length=20)),
                ('season', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('preview', models.ImageField(blank=True, null=True, upload_to=tyresapp.models.tyre_preview_directory_path)),
            ],
        ),
    ]
