# Generated by Django 4.1.7 on 2024-03-28 21:42

from django.db import migrations, models
import django.db.models.deletion
import tyresapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('tyresapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tyre',
            name='status',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.CreateModel(
            name='TyreImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=tyresapp.models.tyre_images_directory_path)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('tyre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tyresapp.tyre')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.IntegerField(default=0)),
                ('receipt', models.FileField(null=True, upload_to='orders/receipts/')),
                ('tyres', models.ManyToManyField(related_name='orders', to='tyresapp.tyre')),
            ],
        ),
    ]
