# Generated by Django 5.0.1 on 2024-03-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyresapp', '0002_tyre_status_tyreimage_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='tyre',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
