# Generated by Django 5.0.1 on 2024-03-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyresapp', '0003_tyre_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tyre',
            name='disks_parameters',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
