# Generated by Django 5.0.1 on 2024-03-29 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tyresapp', '0004_alter_tyre_disks_parameters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tyreimage',
            name='description',
        ),
    ]
