# Generated by Django 5.0.1 on 2024-03-29 12:34

import tyresapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyresapp', '0005_remove_tyreimage_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tyre',
            name='preview',
        ),
        migrations.AlterField(
            model_name='tyreimage',
            name='image',
            field=models.ImageField(upload_to=tyresapp.models.tyre_preview_directory_path),
        ),
    ]
