# Generated by Django 5.0.1 on 2024-03-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyresapp', '0007_alter_tyre_tread_remain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='receipt',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tyres',
        ),
        migrations.AddField(
            model_name='order',
            name='tyre_id',
            field=models.IntegerField(default=0),
        ),
    ]
