# Generated by Django 5.0.1 on 2024-04-29 21:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyresapp', '0008_remove_order_receipt_remove_order_tyres_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filtration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=50)),
                ('subcategory', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sorting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.IntegerField(default=0)),
                ('method', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='tyre',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
