version: "3.8"

services:
  app:
    build:
      dockerfile: ./Dockerfile
    restart: always
    environment:
      DJANGO_LOGLEVEL: INFO
      DJANGO_SECRET_KEY: UMhzQCzgYnoC8b4smzw3Eu
      DJANGO_DEBUG: 1
      DJANGO_ALLOWED_HOSTS: freshautoshop.ru,www.freshautoshop.ru
      VIRTUAL_HOST: freshautoshop.ru,www.freshautoshop.ru
      VIRTUAL_PORT: 8000
      LETSENCRYPT_HOST: freshautoshop.ru,www.freshautoshop.ru
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"
    volumes:
      - "./webapp/database:/app/database"
    networks:
      default:
      proxy:

networks:
  default:
  proxy:
    name: proxy
    external: true
